### ISSUE TITLE
Compilation error with GCC 9.1 in fmt 

### ISSUE THREAD

**Issue by javashin** [citra-emu/citra#4766]
[citra fail build .log](https://github.com/citra-emu/citra/files/3154060/citra.fail.build.log)

**Comment by MerryMage** [comment]
./externals/fmt/include/fmt/format.h:3475:55: error: ISO C++ did not adopt string literal operator 
    templates taking an argument pack of characters [-Wpedantic]
     3475 | FMT_CONSTEXPR internal::udl_formatter<Char, CHARS...> operator""_format() {
          |                                                       ^~~~~~~~
    compilation terminated due to -Wfatal-errors.

Non-standrad feature use in fmt, to be reported upstream.

**Comment by javashin** [comment]
export FMT_USE_USER_DEFINED_LITERALS=0 dont help to compile with gcc 9.1

**Comment by KAMiKAZOW** [comment]
https://github.com/fmtlib/fmt/issues/1148 apparently fixed. Please import the bugfix (yuzu as please).

**Comment by 5schatten** [comment]
@javashin depending on your build system `CXXFLAGS+=" -DFMT_USE_USER_DEFINED_LITERALS=0"` will work

**Comment by javashin** [comment]
yes help thanks

**Comment by wwylele** [comment]
As we have been only tracking fmt stable release, and we don't know when will be the next one, should we add that flag in our CMake as a hotfix?

**Comment by B3n30** [comment]
probably a good idea. at least until the next stable version of fmt is available

**Comment by javashin** [comment]
NICE!
