### ISSUE TITLE
Fails to build on FreeBSD in C++17 mode

### ISSUE THREAD

**Issue by jbeich** [citra-emu/citra#3435]
`__has_feature(cxx_lambda)` returns `0` for Clang which makes bundled cryptopp use `std::bind2nd()` but libc++ in [removed](https://github.com/llvm-mirror/libcxx/commit/059256914c5d) it for C++17. For now, I've temporarily downgraded to C++14 [downstream](https://github.com/freebsd/freebsd-ports/commit/d92d2a9e9b32#diff-fb47999693237700c21e3989b1ffd2e5).

```c++
$ c++ -v
FreeBSD clang version 6.0.0 (branches/release_60 324090) (based on LLVM 6.0.0)
Target: x86_64-unknown-freebsd12.0
Thread model: posix
InstalledDir: /usr/bin

$ git rev-list -1 HEAD
775fb388c29530a9e552da83b7f2ab75e9227e28
$ cmake -DENABLE_QT=off /path/to/citra
$ gmake
[...]
In file included from src/core/file_sys/cia_container.cpp:6:
In file included from externals/cryptopp/./cryptopp/sha.h:12:
In file included from externals/cryptopp/./cryptopp/iterhash.h:7:
In file included from externals/cryptopp/./cryptopp/secblock.h:11:
externals/cryptopp/./cryptopp/misc.h:2542:43: error: no member named 'bind2nd' in namespace 'std'
    return std::find_if(first, last, std::bind2nd(std::not_equal_to<T>(), value));
                                     ~~~~~^
1 error generated.
```
Regressed by ce31cf531d85, see also weidai11/cryptopp@5ae79afd89c9 + weidai11/cryptopp@59b94d2bbf43

**Comment by jbeich** [comment]
Sorry, I've looked at the wrong checkout. libc++ upstream also [removed](https://github.com/llvm-mirror/libcxx/commit/059256914c5d) `std::bind2nd`.
