### ISSUE TITLE
[Feature Request] Raspberry Pi Support

### ISSUE THREAD

**Issue by Kneesnap** [citra-emu/citra#5554]
I would like to request a build for Raspberry Pi 3 / Raspberry Pi 4. This seems like a fairly straightforward task, given there is already support for JIT on ARM. If at all possible, it would be nice to allow for controller configuration and fullscreen-only mode (no X11 requirement). This feature would be very good for anyone running RetroPie, which may not come with a desktop installed. It would also be good to make things configurable completely with a controller, since some hobbyist raspberry pi game consoles don't have a keyboard, or an open port to plug one in.

I would do this myself, but I lack the time it would take to figure out how to do this.

**Comment by NielsGx** [comment]
afaik the rPi 4 4Gb cannot evem run Dolphin at half speed in 3D games.
PPSSPP works well tho

**Comment by Kneesnap** [comment]
I see. I could have sworn I read in another issue that the ARM JIT made
certain 3DS games run at near full speed. It's possible I misunderstood
something though, as it does strike me as unlikely it could run many games
well.

**Comment by Kneesnap** [comment]
I'd still like to play around with this. If I could get a compiled build that'd be good, even if it isn't turned into an official release.

**Comment by Heasterian** [comment]
@Kneesnap I was able to compile Citra on my Jetson Nano. Just have in mind that some OS repositories have wron Qt version at this moment so you can have issues at 94% of compilation. It's trying to use OpenGLES instead of OpenGL. Keep in mind that you also need 64 bit os to run Citra. In my case compilation failed on Ubuntu 18.04, but works fine on 20.04.

**Comment by elliot-sawyer** [comment]
I recently attempted to compile Citra following the Linux instructions for a Debian install on a Pi4.  I got to the "make" step up to 92%, where it fails with the below trace:
```
[ 92%] Linking CXX executable ../../bin/Release/tests
/usr/bin/ld: ../core/CMakeFiles/core.dir/hle/service/http_c.cpp.o: in function `std::_Function_handler<bool (unsigned long long, unsigned long long), Service::HTTP::Context::MakeRequest()::{lambda(unsigned long long, unsigned long long)#2}>::_M_invoke(std::_Any_data const&, unsigned long long&&, std::_Any_data const&)':
http_c.cpp:(.text+0x60): undefined reference to `__atomic_store_8'
/usr/bin/ld: http_c.cpp:(.text+0x78): undefined reference to `__atomic_store_8'
collect2: error: ld returned 1 exit status
make[2]: *** [src/tests/CMakeFiles/tests.dir/build.make:259: bin/Release/tests] Error 1
make[1]: *** [CMakeFiles/Makefile2:2108: src/tests/CMakeFiles/tests.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Comment by elliot-sawyer** [comment]
I got this to build on a Raspberry Pi4 using the 64-bit version of the Raspberry OS. Make sure to install _all_ the dependencies in the list.

**Comment by danrm81** [comment]
i can compile on my pi4 with 64bit os ... but we have only opengl 3.1 . Last citra wont opengl 3.3.

do you know if there is an old version that use opengl 3.1 or les ?

**Comment by hYdos** [comment]
> I got this to build on a Raspberry Pi4 using the 64-bit version of the Raspberry OS. Make sure to install _all_ the dependencies in the list.

where you able to run any roms? i've been able to compile by commenting out some GL 3+ things but when i've ran rom's it seg fault's. probably something i messed up :p

**Comment by elliot-sawyer** [comment]
No ROMs because of the OpenGL thing. I also suspect they will not run well - I have an recent 8-core mobile device that struggles with Citra, I doubt the Pi could keep up with it.

**Comment by hYdos** [comment]
It would be good if we had options to use vulkan or other rendering api's in citra. The Rpi 4 has vulkan support last i checked

**Comment by SchynsO** [comment]
> @Kneesnap I was able to compile Citra on my Jetson Nano. Just have in mind that some OS repositories have wron Qt version at this moment so you can have issues at 94% of compilation. It's trying to use OpenGLES instead of OpenGL. Keep in mind that you also need 64 bit os to run Citra. In my case compilation failed on Ubuntu 18.04, but works fine on 20.04.

Did you manage to compile `citra-qt` or just regular `citra`?
I have a lot of trouble to get it working the way I want it.

**Comment by quimodotcom** [comment]
bump

**Comment by poudink** [comment]
Does Citra work on ARM GNU/Linux at all? Like Ubuntu L4T for the Switch, PostmarketOS for smartphones or Asahi Linux for M1 Macs.

**Comment by Lolothepro** [comment]
Given that Vulkan will be supported by Citra in the future, will it be possible to add support for Raspberry Pi 4(/arm64)?

**Comment by quimodotcom** [comment]
> Citra Canary now compatible with Raspberry Pi Note: #6891

It is not compatible with raspberry pi os which is the main OS for the rpi especially if you want all functionality with less clutter.

**Comment by Lolothepro** [comment]
It is now compatible, you just need to build it yourself.
