### ISSUE TITLE
Linux compilation errors

### ISSUE THREAD

**Issue by 7oxicshadow** [citra-emu/citra#1711]
Building on Linux has started to fail with the following error:

/usr/bin/ld: ../common/libcommon.a(microprofile.cpp.o): undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/citra_qt/citra-qt] Error 1
make[1]: *** [src/citra_qt/CMakeFiles/citra-qt.dir/all] Error 2
make: *** [all] Error 2

**Comment by wwylele** [comment]
This is a regression due to #1576. Add back the flag `-pthread` to [CMakeLists.txt#L68](https://github.com/citra-emu/citra/blob/master/CMakeLists.txt#L68 ) can temporary resolve the problem.

**Comment by ProfessorKaos64** [comment]
I still get this error, even when using CMake 3.5.x (now that the required version must be 3.1x). Build log: https://gist.github.com/ProfessorKaos64/b20ad306331e3ac25c0f0db96033042d

**Comment by jcowgill** [comment]
> c++: internal compiler error: Killed (program cc1plus)

@ProfessorKaos64 That error means you ran out of memory and the OOM killer killed the compiler.

**Comment by ProfessorKaos64** [comment]
Hmm. interesting. Ok, i'll destroy my poor VPS and create one with more RAM :)  Thank you

**Comment by wwylele** [comment]
Still getting error:
```
[100%] Linking CXX executable citra-qt
/usr/bin/ld: ../common/libcommon.a(microprofile.cpp.o): undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/citra_qt/CMakeFiles/citra-qt.dir/build.make:795: recipe for target 'src/citra_qt/citra-qt' failed
make[2]: *** [src/citra_qt/citra-qt] Error 1
CMakeFiles/Makefile2:603: recipe for target 'src/citra_qt/CMakeFiles/citra-qt.dir/all' failed
make[1]: *** [src/citra_qt/CMakeFiles/citra-qt.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
This is onUbuntu 16.04, cmake 3.5.1

**Comment by ProfessorKaos64** [comment]
Same error still as @wwylele reports. Confirmed here as well on Debian 8.

**Comment by ProfessorKaos64** [comment]
I did notice that the main Linux build readme notes you need gcc 5+ now. Only Debian Stretch meets that requirement.  Not sure about Ubuntu. Maybe that is it?

**Comment by wwylele** [comment]
@ProfessorKaos64 Ubuntu 16.04 is with gcc 5.3.1

**Comment by ProfessorKaos64** [comment]
Well that makes me feel better then, i'm sitting at 4.9, and it used to compile. Now I get the errors you get as well. Gives me a bit of hope then.

**Comment by ProfessorKaos64** [comment]
Of note, the temporary workaround with -pthread works. OS their an issue for this to track, or will this be addressed at some point?

**Comment by wwylele** [comment]
@ProfessorKaos64 with #1720 merged now I don't get any more error.

**Comment by 7oxicshadow** [comment]
confirmed fixed with #1720.

**Comment by ProfessorKaos64** [comment]
Saw that commit just now. Thanks :)
