### ISSUE TITLE
file_util.cpp fails under -Werror=ignored-attributes

### ISSUE THREAD

**Issue by HurricanePootis** [citra-emu/citra#6884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Github Head

### Description of Issue

citra fails to compile with `gcc 13.2.1` with the following flags: 
`CFLAGS=-march=znver3 -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection` 
and 
`CXXFLAGS=-march=znver3 -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS`

I get the following error:
```
/home/hurricane/citra-git/src/citra/src/common/file_util.cpp: In function ‘bool FileUtil::Copy(const std::string&, const std::string&)’:
/home/hurricane/citra-git/src/citra/src/common/file_util.cpp:327:70: error: ignoring attributes on template argument ‘int (*)(FILE*)’ [-Werror=ignored-attributes]
  327 |     using CFilePointer = std::unique_ptr<FILE, decltype(&std::fclose)>;
      |                                                                      
```
### Expected Behavior

For the program to compile

### Reproduction Steps

```
git clone --recursive https://github.com/citra-emu/citra && mkdir build
    cmake -B build -S "citra" \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=Release \
      -DENABLE_LTO=ON \
      -DENABLE_QT_TRANSLATION=ON \
      -DCITRA_ENABLE_COMPATIBILITY_REPORTING=ON \
      -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON \
      -DUSE_DISCORD_PRESENCE=ON \
      -DENABLE_FFMPEG_VIDEO_DUMPER=ON \
      -DENABLE_FFMPEG_AUDIO_DECODER=ON \
      -DUSE_SYSTEM_BOOST=OFF \
      -DUSE_SYSTEM_SDL2=ON \
      -DCMAKE_C_COMPILER=gcc \
      -DCMAKE_CXX_COMPILER=g++ \
      -DCMAKE_C_FLAGS="$CFLAGS" \
      -DCMAKE_CXX_FLAGS="$CXXFLAGS" \
      -Wno-dev
```

### Log File

```
/home/hurricane/citra-git/src/citra/src/common/file_util.cpp: In function ‘bool FileUtil::Copy(const std::string&, const std::string&)’:
/home/hurricane/citra-git/src/citra/src/common/file_util.cpp:327:70: error: ignoring attributes on template argument ‘int (*)(FILE*)’ [-Werror=ignored-attributes]
  327 |     using CFilePointer = std::unique_ptr<FILE, decltype(&std::fclose)>;
      |   
```

### System Configuration

CPU: Ryzen 5 5625U
GPU/Driver: Radeon Integrated Graphics (GCN 5th Gen) with Mesa
RAM: 16 GB
OS: Arch Linux
