### ISSUE TITLE
Build error on bootmanager.h

### ISSUE THREAD

**Issue by Alkaris** [citra-emu/citra#854]
Qt fails the `make` process with the following;

    Scanning dependencies of target citra-qt
    [ 85%] Building CXX object src/citra_qt/CMakeFiles/citra-qt.dir/debugger/disassembler.cpp.o
    In file included from /home/alkaris/citra/src/citra_qt/debugger/disassembler.cpp:7:0:
    /home/alkaris/citra/src/citra_qt/debugger/../bootmanager.h:10:21: fatal error: QGLWidget: No such file or directory
     #include <QGLWidget>
                         ^
    compilation terminated.
    make[2]: *** [src/citra_qt/CMakeFiles/citra-qt.dir/debugger/disassembler.cpp.o] Error 1
    make[1]: *** [src/citra_qt/CMakeFiles/citra-qt.dir/all] Error 2
    make: *** [all] Error 2

Should it not be `QtWidget` or `QWidget` ?
I am using `Qt 5.2.1`

**Comment by Syphurith** [comment]
These is `QGLWidget` even in Qt 4.8. It is a renderer class for OpenGL. [Doc Here](http://doc.qt.io/qt-5/qglwidget.html)

**Comment by Alkaris** [comment]
@Syphurith I searched my PATH directory for the QGLWidget for Qt5, but it doesn't exist as it tells me, but it does for Qt4 PATH directory, so what I just did was edit the CMake file to just use Qt4 to build it instead of Qt5.

**Comment by Syphurith** [comment]
@Alkaris Well you could change the issue title now, since it may lead to a bigger problem. I don't suggest you to just change the Qt version. Windows nightly compiled citra contains Qt5, so i think that this header may just have been removed within just a few minor versions.

**Comment by Syphurith** [comment]
Using Git blame, this header was introduced in 05be8d2f0c58f5de56bbf920743f91bd8584b4f2 by mattvail. @Alkaris I think you can contact @bunnei @yuriks for suggestion.

**Comment by yuriks** [comment]
I personally use the latest point version of Qt5 as of the time of writing, and I know @neobrain uses Qt4 fine too. I suspect you simply have an incomplete Qt installation. Make sure you have the Qt5 OpenGL module, in case your distro splits the Qt libraries across several packages.

**Comment by Alkaris** [comment]
@Syphurith Linux actually, not Windows build.

@yuriks I'm pretty sure I do have all the Qt5 OpenGL modules, even did a quick check and update, and I have pretty much the full package of Qt5 installed that can be checked on the installer.

**Comment by yuriks** [comment]
"On the installer"?

**Comment by Alkaris** [comment]
@yuriks yes, the online installer so it gets the latest that's available. https://www.qt.io/download-open-source/

**Comment by Syphurith** [comment]
@yuriks I wonder which version of Qt5 you are using, with its minor version.
It is said that `QGLWidget` is deprecated, and `QOpenGLWidget` is its replacement. [Doc](http://doc.qt.io/qt-5/qopenglwidget.html) [Blog](https://blog.qt.io/blog/2014/09/10/qt-weekly-19-qopenglwidget/)
```
Detailed Description

The QOpenGLWidget class is a widget for rendering OpenGL graphics.

QOpenGLWidget provides functionality for displaying OpenGL graphics integrated into a Qt
application. It is very simple to use: Make your class inherit from it and use the subclass
like any other QWidget, except that you have the choice between using QPainter and standard
OpenGL rendering commands.
```
Also seen from [Qt forum](https://forum.qt.io/topic/14081/qglwidget-error/4). Does it work if you use @#include <QtOpenGL/QGLWidget>@ instead of just @#include <QGLWidget>@ ? I don't know if the file actually lays there.

**Comment by Alkaris** [comment]
@Syphurith I tried that part what a person said in the comments about that, but that didn't work, it just returns error that it can't be found. Also I didn't see any `.pro` files in the git download as some suggest adding `@QT += opengl@` to the file.

**Comment by Syphurith** [comment]
@Alkaris I see. citra is built with CMake and there isn't a `.pro` file. BTW if you just want to try it out, you may find the nightly build.. I'm sorry but i can't help with it. Don't know if simply change `QGLWidget` to `QOpenGLWidget` would break some games..

**Comment by yuriks** [comment]
@Alkaris If you're using the official Qt installer then why are you on version 5.2.1, instead of 5.4.2 which is the latest? For being on an older version, I was expecting you to be using distro packages.

We don't use QMake, but our CMake scripts do request the QOpenGL module. `QGLWidget` is deprecated but hasn't yet been removed. We will not switch to it's newer replacement `QOpenGLWidget` until we drop support for Qt 4.8 and until newer Qt point versions become more widespread. Regardless, `QGLWidget` isn't scheduled to be removed from Qt yet, and from (a search in their bugtracker)[https://bugreports.qt.io/browse/QTBUG-37949?jql=affectedVersion%20%3D%205.2.1%20AND%20text%20~%20%22QGLWidget%22] was definitely present in 5.2.1 should definitely have it.

**Comment by Alkaris** [comment]
@yuriks I have no idea then, it probably failed to update to use that one maybe? I was under the impression that 5.2.1 was the latest and that 5.4.2 was still beta.

**Comment by Alkaris** [comment]
I managed to get Qt to properly update to 5.4.2 and compiled it successfully, but the thing just freezes up with a static image of the background and can't do anything with it.

![shutter_2015-06-13__12_46_06_pm](https://cloud.githubusercontent.com/assets/6682988/8142717/33fa5e7e-11ca-11e5-9fbb-672fda5e7e91.png)

**Comment by yuriks** [comment]
Have you loaded a file? The window stays like that until emulation starts.

**Comment by Alkaris** [comment]
@yuriks I can't, it won't do anything. It just sits like that after running the executable.

**Comment by yuriks** [comment]
You don't have a menu bar? Is Qt yelling bloody murder on stderr?

Anyway, I think we've determined by now that this isn't a Citra bug. For further tech support you should probably pop by in IRC instead, to avoid amassing murderous intent from the people with subscribed to repo notifications.

**Comment by Alkaris** [comment]
Well it looks like you dumb fucks wont help me get this shit working when I ask on IRC.

You cunts seem to think that I'm asking for help with Pirated ROMS but you are fucking wrong. THe emulator doesn't fucking work! it just stays frozen.

**Comment by yuriks** [comment]
I'm 100% sure that your Qt frontend problem is a setup issue on your end or system-specific issue. Neverthless you:
 a) Failed to read the channel topic,
 b) Failed to not pirate your game,
 c) Went on a thundering rage when first warned,
 d) Is now ban evading.

I'm not sure what you expected to achieve with the last two honestly, but there you go.
