### PR TITLE
cryptopp: unbreak build on 32-bit x86

### PR DESCRIPTION
**Pull request by jbeich**
Regressed by #5669. Building via GNUmakefile upstream works fine: adds `-msse4.1 -maes` for `rijndael_simd.cpp`. From [error log](https://github.com/citra-emu/citra/files/7825315/citra-qt5-s20220105.log):
```c++
FAILED: externals/cryptopp/CMakeFiles/cryptopp.dir/cryptopp/rijndael_simd.cpp.o 
/usr/bin/c++ -DARCHITECTURE_x86=1 -DBOOST_DATE_TIME_NO_LIB -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_NO_LIB -DENABLE_FFMPEG_VIDEO_DUMPER  -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include  -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include -std=gnu++17 -MD -MT externals/cryptopp/CMakeFiles/cryptopp.dir/cryptopp/rijndael_simd.cpp.o -MF externals/cryptopp/CMakeFiles/cryptopp.dir/cryptopp/rijndael_simd.cpp.o.d -o externals/cryptopp/CMakeFiles/cryptopp.dir/cryptopp/rijndael_simd.cpp.o -c externals/cryptopp/cryptopp/rijndael_simd.cpp
externals/cryptopp/cryptopp/rijndael_simd.cpp:460:20: error: always_inline function '_mm_loadu_si128' requires target feature 'sse2', but would be inlined into function 'Rijndael_UncheckedSetKey_SSE4_AESNI' that is compiled without support for 'sse2'
    __m128i temp = _mm_loadu_si128(M128_CAST(userKey+keyLen-16));
                   ^
externals/cryptopp/cryptopp/rijndael_simd.cpp:469:32: error: '__builtin_ia32_vec_ext_v4si' needs target feature sse2
        rk[keyLen/4] = rk[0] ^ _mm_extract_epi32(_mm_aeskeygenassist_si128(temp, 0), 3) ^ *(rc++);
                               ^
/usr/lib/clang/10.0.1/include/smmintrin.h:1060:8: note: expanded from macro '_mm_extract_epi32'
  (int)__builtin_ia32_vec_ext_v4si((__v4si)(__m128i)(X), (int)(N))
       ^
externals/cryptopp/cryptopp/rijndael_simd.cpp:469:50: error: '__builtin_ia32_aeskeygenassist128' needs target feature aes
        rk[keyLen/4] = rk[0] ^ _mm_extract_epi32(_mm_aeskeygenassist_si128(temp, 0), 3) ^ *(rc++);
                                                 ^
/usr/lib/clang/10.0.1/include/__wmmintrin_aes.h:136:12: note: expanded from macro '_mm_aeskeygenassist_si128'
  (__m128i)__builtin_ia32_aeskeygenassist128((__v2di)(__m128i)(C), (int)(R))
           ^
externals/cryptopp/cryptopp/rijndael_simd.cpp:481:20: error: '__builtin_ia32_vec_set_v4si' needs target feature sse4.1
            temp = _mm_insert_epi32(temp, rk[11], 3);
                   ^
/usr/lib/clang/10.0.1/include/smmintrin.h:960:12: note: expanded from macro '_mm_insert_epi32'
  (__m128i)__builtin_ia32_vec_set_v4si((__v4si)(__m128i)(X), \
           ^
externals/cryptopp/cryptopp/rijndael_simd.cpp:485:20: error: '__builtin_ia32_vec_set_v4si' needs target feature sse4.1
            temp = _mm_insert_epi32(temp, rk[11], 3);
                   ^
/usr/lib/clang/10.0.1/include/smmintrin.h:960:12: note: expanded from macro '_mm_insert_epi32'
  (__m128i)__builtin_ia32_vec_set_v4si((__v4si)(__m128i)(X), \
           ^
externals/cryptopp/cryptopp/rijndael_simd.cpp:486:31: error: '__builtin_ia32_vec_ext_v4si' needs target feature sse2
            rk[12] = rk[ 4] ^ _mm_extract_epi32(_mm_aeskeygenassist_si128(temp, 0), 2);
                              ^
/usr/lib/clang/10.0.1/include/smmintrin.h:1060:8: note: expanded from macro '_mm_extract_epi32'
  (int)__builtin_ia32_vec_ext_v4si((__v4si)(__m128i)(X), (int)(N))
       ^
externals/cryptopp/cryptopp/rijndael_simd.cpp:486:49: error: '__builtin_ia32_aeskeygenassist128' needs target feature aes
            rk[12] = rk[ 4] ^ _mm_extract_epi32(_mm_aeskeygenassist_si128(temp, 0), 2);
                                                ^
/usr/lib/clang/10.0.1/include/__wmmintrin_aes.h:136:12: note: expanded from macro '_mm_aeskeygenassist_si128'
  (__m128i)__builtin_ia32_aeskeygenassist128((__v2di)(__m128i)(C), (int)(R))
           ^
externals/cryptopp/cryptopp/rijndael_simd.cpp:490:20: error: '__builtin_ia32_vec_set_v4si' needs target feature sse4.1
            temp = _mm_insert_epi32(temp, rk[15], 3);
                   ^
/usr/lib/clang/10.0.1/include/smmintrin.h:960:12: note: expanded from macro '_mm_insert_epi32'
  (__m128i)__builtin_ia32_vec_set_v4si((__v4si)(__m128i)(X), \
           ^
externals/cryptopp/cryptopp/rijndael_simd.cpp:494:20: error: '__builtin_ia32_vec_set_v4si' needs target feature sse4.1
            temp = _mm_insert_epi32(temp, rk[7], 3);
                   ^
/usr/lib/clang/10.0.1/include/smmintrin.h:960:12: note: expanded from macro '_mm_insert_epi32'
  (__m128i)__builtin_ia32_vec_set_v4si((__v4si)(__m128i)(X), \
           ^
externals/cryptopp/cryptopp/rijndael_simd.cpp:510:16: error: always_inline function '_mm_aesimc_si128' requires target feature 'aes', but would be inlined into function 'Rijndael_UncheckedSetKeyRev_AESNI' that is compiled without support for 'aes'
        temp = _mm_aesimc_si128(*M128_CAST(key+i));
               ^
externals/cryptopp/cryptopp/rijndael_simd.cpp:511:29: error: always_inline function '_mm_aesimc_si128' requires target feature 'aes', but would be inlined into function 'Rijndael_UncheckedSetKeyRev_AESNI' that is compiled without support for 'aes'
        *M128_CAST(key+i) = _mm_aesimc_si128(*M128_CAST(key+j));
                            ^
externals/cryptopp/cryptopp/rijndael_simd.cpp:515:25: error: always_inline function '_mm_aesimc_si128' requires target feature 'aes', but would be inlined into function 'Rijndael_UncheckedSetKeyRev_AESNI' that is compiled without support for 'aes'
    *M128_CAST(key+i) = _mm_aesimc_si128(*M128_CAST(key+i));
                        ^
12 errors generated.
```
See also
https://github.com/citra-emu/citra/blob/60d1def6f8923cdc7ee64e087b15461f3723157f/externals/cryptopp/CMakeLists.txt#L237

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5917)

### CODE REVIEW

**Comment by BreadFish64** [comment]
It's a small change so I'm not opposed to it. But do you actually have Citra functioning on a 32-bit system?

**Comment by jbeich** [comment]
Kinda slow but appears to work OK in a 32-bit jail. Tested only on FreeBSD. Note, FreeBSD itself [supports](https://www.freebsd.org/platforms/) i386 on 12.* series as Tier1 [until 2024-06-30](https://www.freebsd.org/security/).

**Comment by jbeich** [comment]
IIRC, 32-bit is slow due to missing dynarmic but still playable. I haven't tried building with `-march=native` though.
