### ISSUE TITLE
SDL2 library broke MacOS compatibility

### ISSUE THREAD

**Issue by MojitoFan** [citra-emu/citra#5606]
Just a heads up: starting with Canary [69ad9dd](https://github.com/citra-emu/citra-canary/commit/69ad9ddbc56bc4a6e3c2c52fb5d063b70309e812) the SDL library for the MacOS binaries is set to be targeted to Catalina, rendering older MacOS versions useless when they still were compatible up to this point. While the binary itself won't launch at all, attempting to run the latest Canary build ([288baa7](https://github.com/citra-emu/citra-canary/commit/288baa78526187cc9a8482cb12b1b912b8b561d8) as of this writing) through command lines returns this:
```
[ComputerName]:~ [username]$ /Applications/Citra/canary/citra PokemonY.cxi
dyld: lazy symbol binding failed: Symbol not found: _objc_alloc_init
  Referenced from: /Applications/Citra/canary/libs/libSDL2-2.0.0.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

dyld: Symbol not found: _objc_alloc_init
  Referenced from: /Applications/Citra/canary/libs/libSDL2-2.0.0.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

Abort trap: 6
```
Has there been a behind-the-curtain update that breaks compatibility with older versions? Or simply a OS target that was reset to default during a SDL2 update?

Tested with MacOS 10.13 High Sierra

EDIT: Nightly 1632 is also affected.

**Comment by MojitoFan** [comment]
> Just a heads up: starting with Canary [69ad9dd](https://github.com/citra-emu/citra-canary/commit/69ad9ddbc56bc4a6e3c2c52fb5d063b70309e812) the SDL library for the MacOS binaries is set to be targeted to Catalina, rendering older MacOS versions useless when they still were compatible up to this point. While the binary itself won't launch at all, attempting to run the latest Canary build through command lines returns this:
> 
> ```
> [ComputerName]:~ [username]$ /Applications/Citra/canary/citra PokemonY.cxi
> dyld: lazy symbol binding failed: Symbol not found: _objc_alloc_init
>   Referenced from: /Applications/Citra/canary/libs/libSDL2-2.0.0.dylib (which was built for Mac OS X 10.15)
>   Expected in: /usr/lib/libobjc.A.dylib
> 
> dyld: Symbol not found: _objc_alloc_init
>   Referenced from: /Applications/Citra/canary/libs/libSDL2-2.0.0.dylib (which was built for Mac OS X 10.15)
>   Expected in: /usr/lib/libobjc.A.dylib
> 
> Abort trap: 6
> ```
> 
> Has there been a behind-the-curtain update that breaks compatibility with older versions? Or simply a OS target that was reset to default during a SDL2 update? Note that this issue is specific to Canary builds.

Tested with MacOS 10.13 High Sierra

**Comment by xhaavardx** [comment]
I can confirm this. I get a similar error: 

`Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Citra/*/citra-qt.app/Contents/MacOS/../Frameworks/libSDL2-2.0.0.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib`

**Comment by xhaavardx** [comment]
Is someone going to look into this? If not, is there a way to download an older version of Citra that actually works?

**Comment by SachinVin** [comment]
Hello, can either of you, test the latest canary and see if it works on 10.13?

**Comment by SachinVin** [comment]
Thanks for checking @xhaavardx, if you get the chance can you also test controller support.
